### PR TITLE
`lock_winrt_module()` to prevent C++/WinRT host module from unloading

### PR DESCRIPTION
**Pull request by oldnewthing**
Active coroutines normally prevent the C++/WinRT host module from unloading because they employ one or more of these techniques:

* They are part of an IAsyncAction or IAsyncOperation, which retains a reference to the host module until they are destructed.
* They explicitly take a reference to their parent object via `get_strong()`.

The missing case is a `fire_and_forget` coroutine that is not an instance member function. (Either a free function or a static member function.) These things are not attached to COM objects and therefore cannot prevent the host DLL from unloading.

The new `wil::lock_winrt_module()` method acquires a reference count on the C++/WinRT host object's module lock (`winrt::get_module_lock()`) and returns an RAII type that releases the reference upon destruction.

Example usage
=============

```cpp
winrt::fire_and_forget DoSomethingInBackground()
{
    // take a strong reference to the host module
    // to prevent premature unload.
    auto module_strong = wil::lock_winrt_module();

    co_await DoStuffThatUpdatesGlobals();

    // module_strong destructor release the reference,
    // allowing the module to be unloaded.
}
```

### CODE REVIEW

**Comment by jonwis** [comment]
This is a common problem even for non-COM/WinRT DLLs as well.  A dll that uses coroutines (or threadpool, or createthread) needs to acquire and pin a module handle and then free it when the work item terminates.

Should the coroutine mechanics also bump the loader's refcount with `GetModuleHandleEx` using the handler function's address to map to a module handle?

**Comment by ChrisGuzak** [comment]
@Jonwis, my understanding is you must call FreeLibraryAndExitThread for that to work. is that possible in the cases you are thinking of?

**Review by ChrisGuzak — APPROVED** [review]

**Comment by sylveon** [comment]
Why not add this to C++/WinRT? Or maybe even make it built-in to `fire_and_forget`?

**Comment by oldnewthing** [comment]
> Why not add this to C++/WinRT? Or maybe even make it built-in to `fire_and_forget`?

C++/WinRT should be focused on the projection. It was not intended to be a general-purpose coroutine library.

Helper functions like this can be provided by outside libraries, just like how System.Threading.Tasks is not part of the Windows Runtime C# projection, but is rather a separate library in the BCL.

**Comment by sylveon** [comment]
Being part of wil certainly makes the discoverability for non-MS employees harder, as wil being public is still relatively recent, and the documentation for C++/WinRT never mentions it.

**Comment by dmachaj** [comment]
This seems genuinely useful and solves a problem.  As-is it is not a lot of code and gets the job done.  It does rely on cppwinrt to do the heavy lifting so I wonder if it would make sense to have an open backlog item to create a version of this that can be used by code bases that don't otherwise rely on cppwinrt.  If that is not widely needed then it can go un-implemented.  If others do need it then someone can add it in the future.

**Comment by oldnewthing** [comment]
> I wonder if it would make sense to have an open backlog item to create a version of this that can be used by code bases that don't otherwise rely on cppwinrt.

Good point. I'll add a WRL version to `cppwinrt_wrl.h`. (Could in theory also add an ATL version, but it looks like WIL doesn't bother supporting ATL, so why start now.)

**Comment by oldnewthing** [comment]
Gonna solve this a different way when I add WRL support. Abandoning this one.

**Pull request closed without merging**
