### PR TITLE
Update readme with vcpkg info

### PR DESCRIPTION
**Pull request by dunhor**
Folks in VS pointed out that the readme hadn't been updated to include information regarding WIL's availability with vcpkg.

### CODE REVIEW

**Comment by KindDragon** [comment]
@sylveon you can build latest commit using `vcpkg install <package> --head`

**Comment by sylveon** [comment]
Nice, I wasn't aware of that. This should totally be mentioned in the readme then.

**Comment by dunhor** [comment]
@KindDragon I'm a bit confused by the expected workflow when using `--head`. For one it doesn't seem possible to "upgrade" an existing package to reference HEAD (at least `vcpkg upgrade` doesn't seem to have any `--head`-equivalent argument and running `vcpkg install` again with `--head` doesn't seem to do it either). AFAICT you have to remove and re-install the package with `--head` for it to work. Not a terrible limitation, but not ideal either.

But what's more annoying is that even if I _do_ install a package with `--head`, I can't seem to figure out how to update it. If I run `vcpkg update` it tells me `Using local portfile versions. To update the local portfiles, use 'git pull'`. Okay, maybe it's doing some special voodoo that hooks into `git pull`, but running `git pull` just seems to no-op (so no voodoo). If I run `vcpkg upgrade` it tells me I need `--no-dry-run` which, if I re-run with that, will revert the package to the version that vcpkg has on record. AFAICT this also requires removing and re-installing the package.

Perhaps `upgrade` has a special argument that I'm missing, but there's no help topic for `upgrade`. Is this expected?

**Comment by ras0219-msft** [comment]
`--head` is intended only as a temporary measure to enable authors to quickly ship fixes for users; the idea is that if someone reports an issue, you can say "Fixed on master -- use `vcpkg install --head` until vcpkg updates to the new version".

For most users, we will be pulling the master commits from here into our catalog regularly (with testing), so we'd recommend leaving the README as just `vcpkg install wil:x64-windows`.

**Comment by dunhor** [comment]
Sounds good. I'll leave it as something for users to discover for themselves if they choose to use that functionality

**Pull request merged**
