### PR TITLE
Sync with OS copy

### PR DESCRIPTION
**Pull request by dunhor**
This is sync'd with commit 9ebe337fed9899a3ca4dae71e713fad8ba6e4b2a

### CODE REVIEW

**Comment by dunhor** [comment]
FYI: I'm planning on updating the NuGet once submitted

**Comment by sylveon** [comment]
Would it also be possible to create a release on GitHub so that the copy on vcpkg can pin to that instead of a random commit?

**Comment by dunhor** [comment]
I suppose we can. @ChrisGuzak any thoughts on a versioning scheme? I was just thinking of just using the date e.g. `20190521` or something like that. I can't really imagine that we'd have a need for `1.X`, `2.X`, etc. releases

**Comment by ras0219-msft** [comment]
If you'd prefer that we follow a rolling-release/evergreen/live-at-head/master model, that's fine by vcpkg as well. We just need clear guidance :)

**Comment by sylveon** [comment]
That'd actually be preferable for me, since I usually make changes to use them straight away in my project (I installed via vcpkg but then just symlinked the installation location to my local clone of wil so that I can git pull the latest changes myself).

**Comment by ras0219-msft** [comment]
I didn't completely follow your setup, however our `--head` switch _might_ be useful for you:
```
vcpkg remove wil
vcpkg install wil --head
```
Will download and install the latest master of `wil` at any point in time.

As for the rolling release, we wouldn't silently upgrade underneath users, but we have ways to automate publishing updates to the vcpkg catalog.

**Comment by dunhor** [comment]
WIL definitely fits more into the "live at head" model

**Pull request merged**
