### PR TITLE
add wil::guid_of specialization for ABI GUID

### PR DESCRIPTION
**Pull request by ChrisGuzak**

### CODE REVIEW

**Comment by jonwis** [comment]
Ok, I'll bite. What's an example of where this is useful?

**Comment by ChrisGuzak** [comment]
> Ok, I'll bite. What's an example of where this is useful?

`auto globalOptions = winrt::create_instance<IGlobalOptions>(wil::guid_of<CLSID_GlobalOptions>());`

**Comment by kennykerr** [comment]
I don't get it. This works just fine without any help from WIL:

```
auto globalOptions = winrt::create_instance<IGlobalOptions>(CLSID_GlobalOptions);
```

**Comment by ChrisGuzak** [comment]
I must not have had unknown.h included first when I tried this. Thanks @Kenny for pointing out this is not needed.

**Pull request closed without merging**
