### PR TITLE
Fixes #13 - Fix typo in spelling of the word "becuase" on line 22 of result_originate.h

### LINKED ISSUE #13: The word "because" is spelled wrong on line 22 of result_originate.h
The word "Because" is spelled wrong on this line (my bad).

https://github.com/Microsoft/wil/blob/a8fbb33b1cdb706c3fd8941693407bd6e145e0d6/include/wil/result_originate.h#L22

### PR DESCRIPTION
**Pull request by dmachaj**

### CODE REVIEW

**Comment by dmachaj** [comment]
Is there a way to associate this with issue #13?

**Comment by dunhor** [comment]
I think that just did it. Out of curiousity, do you see the CI build status?

**Comment by dmachaj** [comment]
I see that the "CLA" requirement is met and that the "Microsoft.wil" Azure pipeline is in progress.

I'm a bit surprised that the "CLA" requirement is met because this is my personal GitHub account that has no association with my official Microsoft credentials.

**Comment by dunhor** [comment]
Excellent. And I think that for simple changes it gets auto approved by LCA IIRC

**Comment by dunhor** [comment]
Since I approved, do you have the option to merge?

**Comment by dmachaj** [comment]
No.  The build is still running.

**Comment by dunhor** [comment]
Okay, cool. I was curious if that would gate completing it.

**Comment by dmachaj** [comment]
Ok everything has completed.  However, I don't see a merge or complete button anywhere.  I'm not sure how to complete the PR.

**Comment by dmachaj** [comment]
pull request
It looks like I'm not allowed to complete it.

**Comment by dunhor** [comment]
Hmm, okay. I was kind of hoping that with sign off and all checks passing it would allow you, but I guess not.

Also, I've just learned that to associate a _fix_ with a bug, you prepend the reference with something like "fixes" (and allegedly other). E.g.

fixes #13

**Comment by dunhor** [comment]
Though maybe because it's not my PR I can't add the tag? Anyway, here's more info on it if you're interested: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by dmachaj** [comment]
It didn't auto-close the issue.  Oh well.  I manually closed it just now.

**Comment by dunhor** [comment]
From the link I posted, it says

> or example, to close an issue numbered 123, you could use the phrase "Closes #123" or "Closes: #123" in your pull request description or commit message. Once the branch is merged into the default branch, the issue will close.

So I'm curious if that implies that it _must_ be in the description or a commit message. Plenty of time to learn, I suppose

**Comment by dmachaj** [comment]
Perhaps "fixes" wasn't the appropriate term and "closes" should have been used instead.  I'm not really familiar with GitHub's terminology on these things.

**Comment by dunhor** [comment]
Any of "close", "closes", "closed", "fix", "fixes", "fixed", "resolve", "resolves", or "resolved" should allegedly work

**Pull request merged**
